version: '3.9'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/userdb  # Indica a database que você quer usar
    volumes:
      - ./app:/app
    depends_on:
      - mongodb
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]  # Garante o comando padrão (opcional se estiver no Dockerfile)

  mongodb:
    image: mongo:6.0  # Usar uma versão específica, mais estável que latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=userdb  # Cria a database inicial "userdb"

volumes:
  mongodb_data: